# Generated by Django 2.2.10 on 2020-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20200304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
    ]
